title: West Coast, Best Coast
author: @katepate
email: emailme@thisdomain.com
description: > # this means to ignore newlines until "baseurl:"
 Want to know about some of the best wine, camping, hiking and swimming the West Coast has to offer? I'm exploring and sharing my discoveries every week. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
